### ISSUE TITLE
簡易ヘッドホンアンプのキットをつくる

### ISSUE THREAD

**Issue by dictav** [WatanabeSeisakujo/NT-Kanazawa#1]
- [ ] 部品を揃えて５セット作成する
- [ ] ドキュメントを作成する
  - [ ] 写真をたくさん撮って公開する

**Comment by fcnt** [comment]
組み立て説明のドキュメントも必要だと思います。担当者と期限を決めないと進まないので、決めて進めましょう。

**Comment by dictav** [comment]
ぼくがドラフト作成するので、添削を @fcnt くんお願いします

**Comment by fcnt** [comment]
わかりました、では一度章立てと各章の概要程度のドラフト版の作成をお願いします。
6/7くらいまでで大丈夫でしょうか?

**Comment by dictav** [comment]
:+1:
