### ISSUE TITLE
展示ボードの準備

### ISSUE THREAD

**Issue by dictav** [WatanabeSeisakujo/NT-Kanazawa#5]
updated at 2015/06/13

展示ボードのサイズは昨年を参考にすると 1200x1800 であると思われます。
http://wiki.nicotech.jp/nico_tech/?NT金沢2014

~~このサイズは、A4 で30枚貼ることができるサイズなので、各員 A4 or A3 で適当に作ってきても貼れるのでサイズは気にしなくて良いです。~~

おそらく背面になると思うので、よりよく見えるようにテーブルから垂らしたり、立て掛けることができるものが必要になりそうです。
## 展示物のポスター
- [ ] 簡易ヘッドホンアンプキット
### fcnt
- [x] 手のひらサイズのFM音源再生ボード
- [ ] RaspberryPi用のFM音源ボード(プロトタイプ)
### daiquiri99
- [ ] 低温調理用AC制御コントローラ
- [ ] PS2bluetoothアダプター or PS2bluetooth化改造済HHKLite
### dictav
- [ ] loltube

**Comment by fcnt** [comment]
## fcnt分の展示物のポスター
- [x] 手のひらサイズのFM音源再生ボード
- [ ] RaspberryPi用のFM音源ボード(プロトタイプ)

CC @dictav @daiquiri99

**Comment by fcnt** [comment]
とりあえず、自分の分はこんな感じで作りました。
各2作品用に詳細を書いたポスターをもう2枚作るつもりです。

http://1drv.ms/1CChvYh

**Comment by dictav** [comment]
すごいいいね！ :+1:

**Comment by dictav** [comment]
ぼくはとりあえずこの１枚になる予定。
https://www.evernote.com/l/AA_ciHxa3UZM35VqPlX7rwTeM6INAGFxyOg

あと、ステッカー作ったので当日配布可能の予定です

**Comment by fcnt** [comment]
カッコいい！
