### ISSUE TITLE
宿泊先について

### ISSUE THREAD

**Issue by daiquiri99** [WatanabeSeisakujo/NT-Kanazawa#7]
## １日目(18日)

| 時間 | 工程 |
| --- | --- |
| 06:00 | fcnt / dictav 宅近くで拾い出発 |
| 10:00 | 会場着 |
| ~~ | NT金沢1日目 |
| 18:00 | 懇親会 |
| ??? | ホテル着 |
## 2日目(19日)

| 時間 | 工程 |
| --- | --- |
| 9:00? | ホテル出発 |
| 10:00 | 会場着 |
| ~~ | NT金沢2日目 |
| 18:00 | 会場発 |
| 24:00 | 新潟着 |

**Comment by daiquiri99** [comment]
宿泊先及び駐車場についてです。

シングル@6400円で3室確保してます。
http://www.alpha-1.co.jp/kanazawa/
僕以外は禁煙室です。

駐車場については、当日10時以降であれば停め置き可能。
翌日は駐車不可なのでチェックアウト後金沢駅近くのパーキングに停める形になりそうです。

**Comment by dictav** [comment]
ありがとうございます。
そういえば、今回の日程ってどうなるんでしたっけ？
#3 で懇親会の話が出ていたのでふと思ったんですが、そもそも２日間フル参加？？
前日入りの話もあった気がしますし、旅行日程を整理したいところ

ページトップに移しました

@fcnt

**Comment by daiquiri99** [comment]
すいません、初日に当日移動という話だったと思っていたのですが違いましたかね？
時間については話して無かったので決める必要ありますね。

**Comment by daiquiri99** [comment]
前日入りになる場合を考えて、同一ホテルを17日も確保しました。
当日までキャンセル可能です。

新潟～金沢間の移動所要時間がだいたい3.5h～4h弱なので

当日移動して１０時の開始時間に間に合わせる場合、６時過ぎに出発する事になると思います。

どちらが良いでしょうか？

**Comment by dictav** [comment]
@fcnt ping

ぼくはどちらのパターンでも大丈夫です。fcntくんに合わせる感じになるかと思います。

**Comment by fcnt** [comment]
17日の予約ありがとうございます。
17日なのですが、どうしても抜けられない職場の飲み会が予定されてしまいました。
(早く抜けられたとしても8時以降と思われます。)

なので、前泊で会場入りは難しいと思っています。
当日の朝出発の案でお願いします。

また、日程については1,2日目ともフルで展示を行い、2日目の展示終了後に新潟に帰るつもりでいましたが、認識合ってます?

**Comment by fcnt** [comment]
もしですが、17日の遅い時間の出発が可能であればそちらに合わせます。

**Comment by dictav** [comment]
@daiquiri99 @fcnt 

ページトップに日程表を追加しました。
認識違いがないか確認ください。
問題あれば早めにfixしましょうー。

**Comment by fcnt** [comment]
日程表ありがとうございます。
これで認識合ってます。

**Comment by fcnt** [comment]
NT金沢の日程について、再度確認しました。
10時に一般会場のため、10時着では遅刻となってしまいます。
やはり9時には金沢駅前入りしていた方が良いと思うので、
出発時間を早めるor前日入りの方向で調整しませんか?

09:00-  出展者開場・準備
10:00-  一般開場
17:00-  閉会・撤収
18:00-20:00 立食パーティー(1日目)・懇親会(2日目)

**Comment by dictav** [comment]
@fcnt 前日入りは難しいと聞いていたので、早朝にするのが良いと思います。
日曜日に調整しましょう

**Comment by fcnt** [comment]
当日早朝出発で決まりました。
- 朝6時新潟出発
- 各自の家に迎えに来てもらう(場所は各自@daiquiriさんに伝える)
